services:
  - type: web
    name: task-calendar-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server/index.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard